name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout mã nguồn
      uses: actions/checkout@v4

    - name: Cài đặt Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Cài đặt Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Cài đặt thư viện dự án
      run: poetry install --no-interaction

    - name: Chạy Pytest & Quét Coverage
      run: |
        poetry run pytest -v --cov=src